version: '3'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:16.0
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./odoo-web-addons:/mnt/extra-addons
      - ./odoo-web-sessions:/var/lib/odoo/.local/share/Odoo/sessions

volumes:
  odoo-db-data:
  odoo-web-data:
  odoo-web-addons:
  odoo-web-sessions:
